USE [master]
GO

/****** Object:  Database [SQLGREENDREAM]    Script Date: 3/2/2018 11:50:15 AM ******/
CREATE DATABASE [SQLGREENDREAM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SQLGREENDREAM', FILENAME = N'S:\SQLDATA\SQLGREENDREAM.mdf' , SIZE = 20480KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SQLGREENDREAM_log', FILENAME = N'S:\SQLLOGS\SQLGREENDREAM_log.ldf' , SIZE = 20480KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [SQLGREENDREAM] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SQLGREENDREAM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SQLGREENDREAM] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SQLGREENDREAM] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SQLGREENDREAM] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SQLGREENDREAM] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SQLGREENDREAM] SET ARITHABORT OFF 
GO

ALTER DATABASE [SQLGREENDREAM] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SQLGREENDREAM] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SQLGREENDREAM] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SQLGREENDREAM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SQLGREENDREAM] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SQLGREENDREAM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SQLGREENDREAM] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SQLGREENDREAM] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SQLGREENDREAM] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SQLGREENDREAM] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SQLGREENDREAM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SQLGREENDREAM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SQLGREENDREAM] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SQLGREENDREAM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SQLGREENDREAM] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SQLGREENDREAM] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SQLGREENDREAM] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SQLGREENDREAM] SET RECOVERY FULL 
GO

ALTER DATABASE [SQLGREENDREAM] SET  MULTI_USER 
GO

ALTER DATABASE [SQLGREENDREAM] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SQLGREENDREAM] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SQLGREENDREAM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SQLGREENDREAM] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SQLGREENDREAM] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SQLGREENDREAM] SET QUERY_STORE = OFF
GO

USE [SQLGREENDREAM]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [SQLGREENDREAM] SET  READ_WRITE 
GO

USE [SQLGREENDREAM]
GO

/****** Object:  StoredProcedure [dbo].[vesql_sp]    Script Date: 3/2/2018 2:32:24 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[vesql_sp]
AS

INSERT INTO tblEmployee 
	SELECT CAST(RAND(CHECKSUM(NEWID())) * 10000 AS INT),
	dbo.udf_StringGenerator('A', 25),
	GETDATE() - ((21 * 365) + RAND()* (39 * 365)),
	Round(CAST(25000 + RAND(CHECKSUM(NEWID())) * 1000000 AS Money),2),
	dbo.udf_StringGenerator('P', 8)

	
GO

USE [SQLGREENDREAM]
GO

/****** Object:  StoredProcedure [dbo].[vesql_sp_deltron]    Script Date: 3/2/2018 2:32:44 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE PROCEDURE [dbo].[vesql_sp_deltron]
AS
DELETE TOP (1) FROM tblEmployee
	
GO



